[package]
name = "nndl-rust"
version = "0.1.0"
authors = ["Nathan Goldbaum <nathan12343@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }